Value=input('Insert something: ')
print('Is in the alphanumeric?\nanswer:',Value.isalnum())
print('Is in the alphabetic?\nanswer:',Value.isalpha())
print('Are all characters in the string ASCII?\nanswer:',Value.isascii())
print('Is a decimal string?\nanswer:',Value.isdecimal())
print('Is a digit string?\nanswer:',Value.isdigit())
print('Is a valid Python identifier?\nanswer:',Value.isidentifier())
print('Is a lowercase string?\nanswer:',Value.islower())
print('Is a whitespace string?\nanswer:',Value.isspace())
print('Is a title-cased string?\nanswer:',Value.istitle())
print('Is an uppercase string?\nanswer:',Value.isupper())